### ISSUE TITLE
iotbx extract_xtal_data.run call signature changed?

### ISSUE THREAD

**Issue by tjlane** [virginia4/isomorphous_maps#6]
I just did a fresh install of cctbx via conda, and had to comment out a few arguments of `extract_xtal_data.run`, which appear to have been removed in the latest version:

```
    determine_data_and_flags_result = extract_xtal_data.run(
        reflection_file_server=reflection_file_server,
        parameters=reflection_data_params,
        #data_parameter_scope="maps.input.reflection_data",
        #flags_parameter_scope="maps.input.reflection_data.r_free_flags",
        #data_description="Reflection data",
        keep_going=True,
        #log=log,
    )
```

Seems to run fine if you just comment out those lines...

**Comment by virginia4** [comment]
Correct, latest version of cctbx only requires the following: 
    determine_data_and_flags_result = extract_xtal_data.run(
        reflection_file_server=reflection_file_server,
        parameters=reflection_data_params,
        keep_going=True,
    )

Also, removing the log, eliminates the output on the screen which is good. Thanks for noticing.
